graph:
  edges:
  - !!python/tuple
    - v0
    - v0
    - strategy: false
      weight: '0'
  - !!python/tuple
    - v0
    - v1
    - strategy: true
      weight: '0'
  - !!python/tuple
    - v1
    - &id001 !!python/tuple
      - v1
      - 1.0
    - strategy: false
      weight: 0
  - !!python/tuple
    - v1
    - &id004 !!python/tuple
      - v1
      - 2.0
    - strategy: true
      weight: 0
  - !!python/tuple
    - vT
    - vT
    - strategy: true
      weight: '-13.0'
  - !!python/tuple
    - *id001
    - vT
    - strategy: false
      weight: 0
  - !!python/tuple
    - &id002 !!python/tuple
      - v2
      - 1.0
    - !!python/tuple
      - v1
      - 1.0
    - strategy: false
      weight: '-2.0'
  - !!python/tuple
    - *id002
    - !!python/tuple
      - v3
      - 1.0
    - strategy: false
      weight: '0.0'
  - !!python/tuple
    - *id002
    - !!python/tuple
      - v4
      - 1.0
    - strategy: false
      weight: '1.0'
  - !!python/tuple
    - &id003 !!python/tuple
      - v3
      - 1.0
    - !!python/tuple
      - v3
      - 1.0
    - strategy: false
      weight: '-0.5'
  - !!python/tuple
    - *id003
    - !!python/tuple
      - v5
      - 1.0
    - strategy: false
      weight: '0.0'
  - !!python/tuple
    - &id009 !!python/tuple
      - v4
      - 1.0
    - !!python/tuple
      - v4
      - 1.0
    - strategy: false
      weight: '0.0'
  - !!python/tuple
    - &id010 !!python/tuple
      - v5
      - 1.0
    - !!python/tuple
      - v4
      - 1.0
    - strategy: false
      weight: '0.0'
  - !!python/tuple
    - *id004
    - !!python/tuple
      - v2
      - 2.0
    - strategy: true
      weight: '0.0'
  - !!python/tuple
    - *id004
    - !!python/tuple
      - v3
      - 2.0
    - strategy: false
      weight: '0.0'
  - !!python/tuple
    - &id005 !!python/tuple
      - v2
      - 2.0
    - !!python/tuple
      - v1
      - 2.0
    - strategy: true
      weight: '-3.0'
  - !!python/tuple
    - *id005
    - !!python/tuple
      - v3
      - 2.0
    - strategy: false
      weight: '-1.0'
  - !!python/tuple
    - *id005
    - !!python/tuple
      - v4
      - 2.0
    - strategy: false
      weight: '0.0'
  - !!python/tuple
    - &id006 !!python/tuple
      - v3
      - 2.0
    - !!python/tuple
      - v3
      - 2.0
    - strategy: true
      weight: '-1.5'
  - !!python/tuple
    - *id006
    - !!python/tuple
      - v5
      - 2.0
    - strategy: false
      weight: '-1.0'
  - !!python/tuple
    - &id007 !!python/tuple
      - v4
      - 2.0
    - !!python/tuple
      - v4
      - 2.0
    - strategy: false
      weight: '-1.0'
  - !!python/tuple
    - *id007
    - !!python/tuple
      - v1
      - 2.0
    - strategy: true
      weight: '0.0'
  - !!python/tuple
    - &id008 !!python/tuple
      - v5
      - 2.0
    - !!python/tuple
      - v4
      - 2.0
    - strategy: false
      weight: '-1.0'
  - !!python/tuple
    - *id008
    - !!python/tuple
      - v5
      - 2.0
    - strategy: true
      weight: '0.0'
  vertices:
  - !!python/tuple
    - v0
    - init: true
      player: adam
  - !!python/tuple
    - v1
    - player: eve
  - !!python/tuple
    - vT
    - player: eve
  - !!python/tuple
    - *id001
    - player: eve
  - !!python/tuple
    - *id002
    - player: adam
  - !!python/tuple
    - *id003
    - player: adam
  - !!python/tuple
    - *id009
    - player: eve
  - !!python/tuple
    - *id010
    - player: eve
  - !!python/tuple
    - *id004
    - player: eve
  - !!python/tuple
    - *id005
    - player: adam
  - !!python/tuple
    - *id006
    - player: adam
  - !!python/tuple
    - *id007
    - player: eve
  - !!python/tuple
    - *id008
    - player: eve
