graph:
  edges:
  - !!python/tuple
    - v1
    - v2
    - weight: '1'
  - !!python/tuple
    - v1
    - v3
    - weight: '1'
  - !!python/tuple
    - v2
    - v1
    - weight: '-1'
  - !!python/tuple
    - v2
    - v4
    - weight: '2'
  - !!python/tuple
    - v3
    - v3
    - weight: '0.5'
  - !!python/tuple
    - v3
    - v5
    - weight: '1'
  - !!python/tuple
    - v5
    - v5
    - weight: '1'
  - !!python/tuple
    - v4
    - v4
    - weight: '2'
  vertices:
  - !!python/tuple
    - v1
    - init: true
      player: eve
  - !!python/tuple
    - v2
    - player: adam
  - !!python/tuple
    - v3
    - player: adam
  - !!python/tuple
    - v5
    - player: eve
  - !!python/tuple
    - v4
    - player: eve
