# defines the final state probability needed for a state to be accepting
# (DEPRECATED)
beta: 0.90

# number of symbols in pdfa alphabet
alphabet_size: 5

# number of states in pdfa state space
num_states: 4

# symbol to use as the transition to a final state
final_transition_sym: '$'

# symbol to use as the empty (a.k.a. lambda) symbol
empty_transition_sym: 'lambda'

# unique start state string label of pdfa
start_state: 'q0'

# whether or not to smooth the input sym. transition distributions
smooth_transitions: False

# define a list of node labels, where each label is a string identifier label
# for a unique node, and the metadata properties for each node
nodes:

  'q0':
    final_probability: 0.0
    trans_distribution: null
    is_accepting: null

  'q1':
    final_probability: 0.2
    trans_distribution: null
    is_accepting: null

  'q2':
    final_probability: 0.8
    trans_distribution: null
    is_accepting: null

# define the edges of the graph
edges:

  'q0':
    'q1':
      symbols:
        - 'a'
      probabilities:
        - 0.4
    'q2':
      symbols:
        - 'b'
      probabilities:
        - 0.6

  'q1':
    'q2':
      symbols:
        - 'b'
      probabilities:
        - 0.8

  'q2':
    'q1':
      symbols:
        - 'a'
      probabilities:
        - 0.2
