alphabet_size: 25
edges:
- !!python/tuple
  - &id001 !!python/tuple
    - s1
    - 0
  - !!python/tuple
    - h12
    - '0'
  - actions: s12
    weight: 0
- !!python/tuple
  - *id001
  - !!python/tuple
    - h13
    - '0'
  - actions: s13
    weight: -3
- !!python/tuple
  - &id002 !!python/tuple
    - s1
    - 1
  - !!python/tuple
    - s2
    - 1
  - actions: s12
    weight: 0
- !!python/tuple
  - *id002
  - !!python/tuple
    - s3
    - 1
  - actions: s13
    weight: -3
- !!python/tuple
  - &id003 !!python/tuple
    - s2
    - 0
  - !!python/tuple
    - h21
    - '0'
  - actions: s21
    weight: -2
- !!python/tuple
  - *id003
  - !!python/tuple
    - h23
    - '0'
  - actions: s23
    weight: -3
- !!python/tuple
  - &id004 !!python/tuple
    - s2
    - 1
  - !!python/tuple
    - s1
    - 1
  - actions: s21
    weight: -2
- !!python/tuple
  - *id004
  - !!python/tuple
    - s3
    - 1
  - actions: s23
    weight: -3
- !!python/tuple
  - &id010 !!python/tuple
    - s3
    - 0
  - !!python/tuple
    - h31
    - '0'
  - actions: s31
    weight: -5
- !!python/tuple
  - &id011 !!python/tuple
    - s3
    - 1
  - !!python/tuple
    - s1
    - 1
  - actions: s31
    weight: -5
- !!python/tuple
  - &id005 !!python/tuple
    - h12
    - '0'
  - !!python/tuple
    - s2
    - 0
  - actions: s12
    weight: 0
- !!python/tuple
  - *id005
  - !!python/tuple
    - s1
    - 1
  - actions: m
    weight: 0
- !!python/tuple
  - *id005
  - !!python/tuple
    - s3
    - 1
  - actions: m
    weight: 0
- !!python/tuple
  - &id006 !!python/tuple
    - h13
    - '0'
  - !!python/tuple
    - s3
    - 0
  - actions: s13
    weight: -3
- !!python/tuple
  - *id006
  - !!python/tuple
    - s2
    - 1
  - actions: m
    weight: 0
- !!python/tuple
  - *id006
  - !!python/tuple
    - s1
    - 1
  - actions: m
    weight: 0
- !!python/tuple
  - &id007 !!python/tuple
    - h21
    - '0'
  - !!python/tuple
    - s1
    - 0
  - actions: s21
    weight: -2
- !!python/tuple
  - *id007
  - !!python/tuple
    - s2
    - 1
  - actions: m
    weight: 0
- !!python/tuple
  - *id007
  - !!python/tuple
    - s3
    - 1
  - actions: m
    weight: 0
- !!python/tuple
  - &id008 !!python/tuple
    - h23
    - '0'
  - !!python/tuple
    - s3
    - 0
  - actions: s23
    weight: -3
- !!python/tuple
  - *id008
  - !!python/tuple
    - s2
    - 1
  - actions: m
    weight: 0
- !!python/tuple
  - *id008
  - !!python/tuple
    - s1
    - 1
  - actions: m
    weight: 0
- !!python/tuple
  - &id009 !!python/tuple
    - h31
    - '0'
  - !!python/tuple
    - s1
    - 0
  - actions: s31
    weight: -5
- !!python/tuple
  - *id009
  - !!python/tuple
    - s2
    - 1
  - actions: m
    weight: 0
- !!python/tuple
  - *id009
  - !!python/tuple
    - s3
    - 1
  - actions: m
    weight: 0
nodes:
- !!python/tuple
  - *id001
  - ap: b
    player: eve
- !!python/tuple
  - *id002
  - ap: b
    player: eve
- !!python/tuple
  - *id003
  - ap: a
    init: true
    player: eve
- !!python/tuple
  - *id004
  - ap: a
    player: eve
- !!python/tuple
  - *id010
  - ap: c
    player: eve
- !!python/tuple
  - *id011
  - ap: c
    player: eve
- !!python/tuple
  - *id005
  - player: adam
- !!python/tuple
  - *id006
  - player: adam
- !!python/tuple
  - *id007
  - player: adam
- !!python/tuple
  - *id008
  - player: adam
- !!python/tuple
  - *id009
  - player: adam
num_obs: 3
num_states: 11
start_state: *id003
