graph:
  edges:
  - !!python/tuple
    - &id001 !!python/tuple
      - s1
      - 0
    - !!python/tuple
      - h12
      - '0'
    - actions: E
      weight: '-4'
  - !!python/tuple
    - *id001
    - !!python/tuple
      - h14
      - '0'
    - actions: W
      weight: '-2'
  - !!python/tuple
    - &id002 !!python/tuple
      - s1
      - 1
    - !!python/tuple
      - s2
      - 1
    - actions: E
      weight: '-4'
  - !!python/tuple
    - *id002
    - !!python/tuple
      - s4
      - 1
    - actions: W
      weight: '-2'
  - !!python/tuple
    - &id003 !!python/tuple
      - s2
      - 0
    - !!python/tuple
      - h21
      - '0'
    - actions: W
      weight: '-2'
  - !!python/tuple
    - *id003
    - !!python/tuple
      - h23
      - '0'
    - actions: S
      weight: '-3'
  - !!python/tuple
    - *id003
    - !!python/tuple
      - h25
      - '0'
    - actions: E
      weight: '-4'
  - !!python/tuple
    - &id004 !!python/tuple
      - s2
      - 1
    - !!python/tuple
      - s1
      - 1
    - actions: W
      weight: '-2'
  - !!python/tuple
    - *id004
    - !!python/tuple
      - s3
      - 1
    - actions: S
      weight: '-3'
  - !!python/tuple
    - *id004
    - !!python/tuple
      - s5
      - 1
    - actions: E
      weight: '-4'
  - !!python/tuple
    - &id005 !!python/tuple
      - s3
      - 0
    - !!python/tuple
      - h32
      - '0'
    - actions: N
      weight: '-9'
  - !!python/tuple
    - *id005
    - !!python/tuple
      - h34
      - '0'
    - actions: S
      weight: '-3'
  - !!python/tuple
    - &id006 !!python/tuple
      - s3
      - 1
    - !!python/tuple
      - s2
      - 1
    - actions: N
      weight: '-9'
  - !!python/tuple
    - *id006
    - !!python/tuple
      - s4
      - 1
    - actions: S
      weight: '-3'
  - !!python/tuple
    - &id007 !!python/tuple
      - s4
      - 0
    - !!python/tuple
      - h43
      - '0'
    - actions: N
      weight: '-9'
  - !!python/tuple
    - *id007
    - !!python/tuple
      - h41
      - '0'
    - actions: W
      weight: '-2'
  - !!python/tuple
    - *id007
    - !!python/tuple
      - h45
      - '0'
    - actions: E
      weight: '-4'
  - !!python/tuple
    - &id008 !!python/tuple
      - s4
      - 1
    - !!python/tuple
      - s3
      - 1
    - actions: N
      weight: '-9'
  - !!python/tuple
    - *id008
    - !!python/tuple
      - s1
      - 1
    - actions: W
      weight: '-2'
  - !!python/tuple
    - *id008
    - !!python/tuple
      - s5
      - 1
    - actions: E
      weight: '-4'
  - !!python/tuple
    - &id009 !!python/tuple
      - s5
      - 0
    - !!python/tuple
      - h54
      - '0'
    - actions: S
      weight: '-3'
  - !!python/tuple
    - *id009
    - !!python/tuple
      - h52
      - '0'
    - actions: N
      weight: '-9'
  - !!python/tuple
    - &id010 !!python/tuple
      - s5
      - 1
    - !!python/tuple
      - s4
      - 1
    - actions: S
      weight: '-3'
  - !!python/tuple
    - *id010
    - !!python/tuple
      - s2
      - 1
    - actions: N
      weight: '-9'
  - !!python/tuple
    - &id011 !!python/tuple
      - h12
      - '0'
    - !!python/tuple
      - s2
      - 0
    - actions: E
      weight: '-4'
  - !!python/tuple
    - *id011
    - !!python/tuple
      - s5
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - *id011
    - !!python/tuple
      - s3
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - *id011
    - !!python/tuple
      - s1
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - *id011
    - !!python/tuple
      - s4
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - &id012 !!python/tuple
      - h14
      - '0'
    - !!python/tuple
      - s4
      - 0
    - actions: W
      weight: '-2'
  - !!python/tuple
    - *id012
    - !!python/tuple
      - s5
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - *id012
    - !!python/tuple
      - s3
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - *id012
    - !!python/tuple
      - s1
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - *id012
    - !!python/tuple
      - s2
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - &id013 !!python/tuple
      - h21
      - '0'
    - !!python/tuple
      - s1
      - 0
    - actions: W
      weight: '-2'
  - !!python/tuple
    - *id013
    - !!python/tuple
      - s5
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - *id013
    - !!python/tuple
      - s3
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - *id013
    - !!python/tuple
      - s4
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - *id013
    - !!python/tuple
      - s2
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - &id014 !!python/tuple
      - h23
      - '0'
    - !!python/tuple
      - s3
      - 0
    - actions: S
      weight: '-3'
  - !!python/tuple
    - *id014
    - !!python/tuple
      - s5
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - *id014
    - !!python/tuple
      - s1
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - *id014
    - !!python/tuple
      - s4
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - *id014
    - !!python/tuple
      - s2
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - &id015 !!python/tuple
      - h25
      - '0'
    - !!python/tuple
      - s5
      - 0
    - actions: E
      weight: '-4'
  - !!python/tuple
    - *id015
    - !!python/tuple
      - s3
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - *id015
    - !!python/tuple
      - s1
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - *id015
    - !!python/tuple
      - s4
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - *id015
    - !!python/tuple
      - s2
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - &id016 !!python/tuple
      - h32
      - '0'
    - !!python/tuple
      - s2
      - 0
    - actions: N
      weight: '-9'
  - !!python/tuple
    - *id016
    - !!python/tuple
      - s5
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - *id016
    - !!python/tuple
      - s3
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - *id016
    - !!python/tuple
      - s1
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - *id016
    - !!python/tuple
      - s4
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - &id017 !!python/tuple
      - h34
      - '0'
    - !!python/tuple
      - s4
      - 0
    - actions: S
      weight: '-3'
  - !!python/tuple
    - *id017
    - !!python/tuple
      - s5
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - *id017
    - !!python/tuple
      - s3
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - *id017
    - !!python/tuple
      - s1
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - *id017
    - !!python/tuple
      - s2
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - &id018 !!python/tuple
      - h43
      - '0'
    - !!python/tuple
      - s3
      - 0
    - actions: N
      weight: '-9'
  - !!python/tuple
    - *id018
    - !!python/tuple
      - s5
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - *id018
    - !!python/tuple
      - s1
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - *id018
    - !!python/tuple
      - s4
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - *id018
    - !!python/tuple
      - s2
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - &id019 !!python/tuple
      - h41
      - '0'
    - !!python/tuple
      - s1
      - 0
    - actions: W
      weight: '-2'
  - !!python/tuple
    - *id019
    - !!python/tuple
      - s5
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - *id019
    - !!python/tuple
      - s3
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - *id019
    - !!python/tuple
      - s4
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - *id019
    - !!python/tuple
      - s2
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - &id020 !!python/tuple
      - h45
      - '0'
    - !!python/tuple
      - s5
      - 0
    - actions: E
      weight: '-4'
  - !!python/tuple
    - *id020
    - !!python/tuple
      - s3
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - *id020
    - !!python/tuple
      - s1
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - *id020
    - !!python/tuple
      - s4
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - *id020
    - !!python/tuple
      - s2
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - &id021 !!python/tuple
      - h54
      - '0'
    - !!python/tuple
      - s4
      - 0
    - actions: S
      weight: '-3'
  - !!python/tuple
    - *id021
    - !!python/tuple
      - s5
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - *id021
    - !!python/tuple
      - s3
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - *id021
    - !!python/tuple
      - s1
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - *id021
    - !!python/tuple
      - s2
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - &id022 !!python/tuple
      - h52
      - '0'
    - !!python/tuple
      - s2
      - 0
    - actions: N
      weight: '-9'
  - !!python/tuple
    - *id022
    - !!python/tuple
      - s5
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - *id022
    - !!python/tuple
      - s3
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - *id022
    - !!python/tuple
      - s1
      - 1
    - actions: m
      weight: '0'
  - !!python/tuple
    - *id022
    - !!python/tuple
      - s4
      - 1
    - actions: m
      weight: '0'
  vertices:
  - !!python/tuple
    - *id001
    - ap: b
      init: true
      player: eve
  - !!python/tuple
    - *id002
    - ap: b
      player: eve
  - !!python/tuple
    - *id003
    - ap: i
      player: eve
  - !!python/tuple
    - *id004
    - ap: i
      player: eve
  - !!python/tuple
    - *id005
    - ap: r
      player: eve
  - !!python/tuple
    - *id006
    - ap: r
      player: eve
  - !!python/tuple
    - *id007
    - ap: g
      player: eve
  - !!python/tuple
    - *id008
    - ap: g
      player: eve
  - !!python/tuple
    - *id009
    - ap: d
      player: eve
  - !!python/tuple
    - *id010
    - ap: d
      player: eve
  - !!python/tuple
    - *id011
    - player: adam
  - !!python/tuple
    - *id012
    - player: adam
  - !!python/tuple
    - *id013
    - player: adam
  - !!python/tuple
    - *id014
    - player: adam
  - !!python/tuple
    - *id015
    - player: adam
  - !!python/tuple
    - *id016
    - player: adam
  - !!python/tuple
    - *id017
    - player: adam
  - !!python/tuple
    - *id018
    - player: adam
  - !!python/tuple
    - *id019
    - player: adam
  - !!python/tuple
    - *id020
    - player: adam
  - !!python/tuple
    - *id021
    - player: adam
  - !!python/tuple
    - *id022
    - player: adam
