alphabet_size: 8
edges:
- !!python/tuple
  - v1
  - v2
  - weight: '1'
- !!python/tuple
  - v1
  - v3
  - strategy: true
    weight: '1'
- !!python/tuple
  - v2
  - v1
  - strategy: true
    weight: '-1'
- !!python/tuple
  - v2
  - v4
  - weight: '2'
- !!python/tuple
  - v3
  - v3
  - strategy: true
    weight: '0.5'
- !!python/tuple
  - v3
  - v5
  - weight: '1'
- !!python/tuple
  - v5
  - v5
  - strategy: true
    weight: '1'
- !!python/tuple
  - v4
  - v4
  - strategy: true
    weight: '2'
nodes:
- !!python/tuple
  - v1
  - init: true
    player: eve
- !!python/tuple
  - v2
  - player: adam
- !!python/tuple
  - v3
  - player: adam
- !!python/tuple
  - v5
  - player: eve
- !!python/tuple
  - v4
  - player: eve
num_obs: 3
num_states: 5
start_state: v1
